// ─── Navigation ────────────────────────────────────────────────────────────────
// Each entry: [href, translationIndex]
export const navItems = [
  ['#hero', 0],
  ['#about', 1],
  ['#education', 2],
  ['#certifications', 3],
  ['#projects', 4],
  ['#gallery', 5],
  ['#experience', 6],
  ['#github-section', 7],
  ['#contact', 8],
];

// ─── Marquee ────────────────────────────────────────────────────────────────────
export const marqueeItems = [
  'React', 'Next.js', 'Node.js', 'TypeScript', 'GSAP', 'Tailwind CSS',
  'MongoDB', 'PostgreSQL', 'Docker', 'AWS', 'Figma', 'Python',
];

// ─── Skills ─────────────────────────────────────────────────────────────────────
// Order matches translation keys: t.skills[0..3]
export const skillGroups = [
  ['React', 'Next.js', 'TypeScript', 'GSAP', 'Tailwind', 'Three.js'],
  ['Node.js', 'Express', 'Python', 'FastAPI', 'GraphQL', 'REST APIs'],
  ['MongoDB', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'Vercel'],
  ['Figma', 'Git', 'Postman', 'VS Code', 'Linux'],
];

// ─── Certifications ───────────────────────────────────────────────────────────
export const certificationItems = [
  {
    issuer: 'MongoDB',
    issuerKey: 'mongodb',
    initials: 'MDB',
    icon: 'database',
    featured: true,
    title: 'MongoDB Overview: Core Concepts and Architecture',
    issued: '2026-02',
    credentialUrl: 'https://www.credly.com/badges/ef0e21de-dfb9-4c2e-8cc2-106d03019eb2/linked_in_profile',
    tags: ['Database', 'Architecture'],
  },
  {
    issuer: 'Cisco',
    issuerKey: 'cisco',
    initials: 'C',
    icon: 'shield',
    featured: true,
    title: 'Cyber Threat Management',
    issued: '2025-05',
    credentialUrl: 'https://www.credly.com/badges/cd88a0f7-7057-4c5d-a273-dade6a3859ff/linked_in_profile',
    tags: ['Cybersecurity', 'Threats'],
  },
  {
    issuer: 'Cisco',
    issuerKey: 'cisco',
    initials: 'C',
    icon: 'network',
    featured: true,
    title: 'Introduction to IoT',
    issued: '2025-05',
    credentialUrl: 'https://www.credly.com/badges/7decd3be-18fc-4705-9b76-b0119b53fb0a/linked_in_profile',
    tags: ['IoT', 'Networks'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'workflow',
    featured: true,
    title: 'Machine Learning Operations (MLOps) for Generative AI',
    issued: '2024-11',
    credentialCode: '12727379',
    credentialUrl: 'https://www.cloudskillsboost.google/public_profiles/9c2ae7c9-1702-4875-beef-1cef5f9b4bc9/badges/12727379',
    tags: ['GenAI', 'MLOps'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'document-ai',
    featured: true,
    title: 'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG Skill Badge',
    issued: '2024-11',
    credentialUrl: 'https://www.credly.com/badges/fdeadce7-3d16-4df5-a98b-5268740d7a6e/linked_in_profile',
    tags: ['Gemini', 'RAG'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'app-code',
    featured: true,
    title: 'Develop GenAI Apps with Gemini and Streamlit Skill Badge',
    issued: '2024-10',
    credentialUrl: 'https://www.credly.com/badges/9cba70b8-3501-41a9-a04b-10aa85951600/linked_in_profile',
    tags: ['Gemini', 'Apps'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'shield',
    featured: true,
    title: 'Gemini for Security Engineers',
    issued: '2024-10',
    credentialCode: '12217020',
    credentialUrl: 'https://www.cloudskillsboost.google/public_profiles/9c2ae7c9-1702-4875-beef-1cef5f9b4bc9/badges/12217020',
    tags: ['Gemini', 'Security'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'cloud',
    featured: true,
    title: 'Gemini for Cloud Architects',
    issued: '2024-10',
    credentialCode: '12169885',
    credentialUrl: 'https://www.cloudskillsboost.google/public_profiles/9c2ae7c9-1702-4875-beef-1cef5f9b4bc9/badges/12169885',
    tags: ['Gemini', 'Cloud'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'balance',
    featured: true,
    title: 'Responsible AI: Applying AI Principles with Google Cloud',
    issued: '2024-10',
    credentialCode: '12004983',
    credentialUrl: 'https://www.cloudskillsboost.google/public_profiles/9c2ae7c9-1702-4875-beef-1cef5f9b4bc9/badges/12004983',
    tags: ['AI Principles', 'Cloud'],
  },
  {
    issuer: 'Google',
    issuerKey: 'google',
    initials: 'G',
    icon: 'prompt',
    featured: true,
    title: 'Prompt Design in Vertex AI Skill Badge',
    issued: '2024-10',
    credentialUrl: 'https://www.credly.com/badges/6a5fca27-b46c-4794-a8ca-ff05f6bb4891/linked_in_profile',
    tags: ['Vertex AI', 'Prompting'],
  },
  {
    issuer: 'Cisco Networking Academy',
    issuerKey: 'cisco-academy',
    initials: 'CNA',
    icon: 'network',
    title: 'Cisco Certified Networking Essentials',
    issued: '2024-03',
    tags: ['Networking', 'Security'],
  },
  {
    issuer: 'DIO',
    issuerKey: 'dio',
    initials: 'DIO',
    icon: 'sparkles',
    title: 'Introdução à Inteligência Artificial - Microsoft Copilot AI',
    issued: '2024-08',
    credentialCode: '4LWE2RCQ',
    tags: ['Copilot', 'AI'],
  },
  {
    issuer: 'Inova CPS',
    issuerKey: 'inova-cps',
    initials: 'CPS',
    icon: 'lightbulb',
    title: 'Escola de Inovadores',
    issued: '2022-12',
    credentialCode: '638a927e-0be4-42bc-a86a-2c050a0000b1',
    tags: ['Innovation', 'Product'],
  },
  {
    issuer: 'Fundação Bradesco Escola Virtual',
    issuerKey: 'bradesco',
    initials: 'FB',
    icon: 'lock',
    title: 'Lei Geral de Proteção de Dados (LGPD)',
    issued: '2022-10',
    credentialCode: 'CC7DDCA9-3AFA-4AC8-A1EB-946AA6B2AF97',
    tags: ['Privacy', 'Security'],
  },
  {
    issuer: 'Fundação Bradesco Escola Virtual',
    issuerKey: 'bradesco',
    initials: 'FB',
    icon: 'shield',
    title: 'Segurança em Tecnologia da Informação',
    issued: '2022-10',
    credentialCode: 'B96C470E-673D-4F89-A3F5-C8DD3F102489',
    tags: ['Security', 'IT'],
  },
  {
    issuer: 'Fundação Bradesco Escola Virtual',
    issuerKey: 'bradesco',
    initials: 'FB',
    icon: 'code',
    title: 'Linguagem de Programação Java - Avançado',
    issued: '2022-10',
    credentialCode: '996EA5EC-4525-42B5-A231-178AC8AC556D',
    tags: ['Java', 'Programming'],
  },
  {
    issuer: 'Fundação Bradesco',
    issuerKey: 'bradesco',
    initials: 'FB',
    icon: 'code',
    title: 'Linguagem de Programação Java - Básico',
    issued: '2022-10',
    credentialCode: 'EA2972C8-F15B-4CC7-8E0C-9D4A016D8558',
    tags: ['Java SE', 'Programming'],
  },
  {
    issuer: 'Fundação Bradesco',
    issuerKey: 'bradesco',
    initials: 'FB',
    icon: 'spreadsheet',
    title: 'Microsoft Excel 2016 - Intermediário',
    issued: '2023-04',
    credentialCode: '01C060AC-D49C-4CC6-B41B-18C9137DD2ED',
    tags: ['Excel', 'Office'],
  },
  {
    issuer: 'Fundação Bradesco',
    issuerKey: 'bradesco',
    initials: 'FB',
    icon: 'spreadsheet',
    title: 'Microsoft Excel 2016 - Básico',
    issued: '2023-03',
    credentialCode: '2A5F576B-319F-41EC-ABCF-7355D99F548E',
    tags: ['Excel', 'Office'],
  },
  {
    issuer: 'Cisco Networking Academy',
    issuerKey: 'cisco-academy',
    initials: 'CNA',
    icon: 'terminal',
    title: 'NDG Linux Unhatched',
    issued: '2023-04',
    credentialCode: '1048098474',
    tags: ['Linux', 'Kernel'],
  },
];

// ─── Projects ───────────────────────────────────────────────────────────────────
// Each entry: [name, imageUrl, techBadges[], githubUrl]
// githubUrl is optional — leave as '' if no public repo yet
export const projects = [
  ['LogiStruct ERP',            'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80', ['Go', 'Rust', 'GraphQL', 'PostgreSQL'],  'https://github.com/danmarquees/logistruct'],
  ['SGH Dispenser',             'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&q=80', ['React', 'Dashboard', 'RBAC'],          ''],
  ['Personal Portfolio',        'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80', ['React', 'GSAP', 'Security'],        'https://github.com/danmarquees/portfolio'],
  ['MetricPath',                'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&q=80', ['TypeScript', 'React', 'Django'],    'https://github.com/danmarquees/metricpath'],
  ['Sentimind API',             'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80', ['Python', 'REST API', 'AI'],         'https://github.com/danmarquees/sentimind-api'],
  ['Kafka Fraud Detection',     'https://images.unsplash.com/photo-1605379399642-870262d3d051?w=600&q=80', ['Java', 'Kafka', 'Data'],            'https://github.com/danmarquees/kafka-fraud-detection'],
];

// ─── Gallery ────────────────────────────────────────────────────────────────────
// Each entry: [spanClass, category, imageUrl, altText]
export const galleryItems = [
  ['g1', 'ui',     'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80', 'Abstract gradient UI'],
  ['g2', 'web',    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80',   'Code editor dark theme'],
  ['g3', 'brand',  'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=600&q=80', 'Branding mockup'],
  ['g4', 'motion', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',   'Motion graphics neon'],
  ['g5', 'ui',     'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',   'UI design system'],
  ['g6', 'web',    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',   'Dashboard analytics'],
  ['g7', 'brand',  'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&q=80', 'Typography poster'],
  ['g8', 'motion', 'https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=600&q=80', '3D render abstract'],
  ['g9', 'ui',     'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&q=80', 'Mobile app mockup'],
];

export const filterKeys = ['all', 'ui', 'web', 'motion', 'brand'];

// ─── Breadcrumb ─────────────────────────────────────────────────────────────────
// Each entry: [href, label]
export const breadcrumbSections = [
  ['#hero',           'Home'],
  ['#about',          'About'],
  ['#education',      'Education'],
  ['#certifications', 'Certifications'],
  ['#projects',       'Projects'],
  ['#gallery',        'Gallery'],
  ['#experience',     'Experience'],
  ['#github-section', 'GitHub'],
  ['#contact',        'Contact'],
];
